### PR TITLE
Added audio controller class example

### PR DESCRIPTION
**Pull request by Lorenzsj**
Added examples of how to set, decrease and increase a process' volume.

### CODE REVIEW

**Comment by AndreMiras** [comment]
Great, I'm glad you found a way to change volume per process.
I happy you made a pull request.
Like I said I'm don't have a Windows computer to review and test and I'm getting busy on different subjects.
But I'll definitely review when I get a chance to.
Thanks again!

**Comment by Floyer007** [comment]
Thank you for the example!
Works perfectly on my Windows 8 machine.

Hope it will be pulled one day.

**Comment by AndreMiras** [comment]
Thank you again @Lorenzsj sorry for the super long delay, I'm busy on other projects.
Thank you @Floyer007 for voting for this issue to speed it up ;)

**Comment by Floyer007** [comment]
No problem :)

**Pull request merged**
