### PR TITLE
Added IAudioSessionEvents callbacks & Example

### PR DESCRIPTION
**Pull request by TurboAnonym**
Implementing https://github.com/AndreMiras/pycaw/issues/27 and more usefull callbacks!

Following "IAudioSessionEvents" callbacks are supported:
OnSimpleVolumeChanged()
OnStateChanged()
OnSessionDisconnected()

Added an example to show the new features

Thanks @AndreMiras for this project!

### CODE REVIEW

**Comment by TurboAnonym** [comment]
Oooooops that where a lot of commits ;)

Its my first time contributing to Github ^^

But now everything should work as expected!

**Comment by TurboAnonym** [comment]
I think i will come back later with an even bigger pull request ;)

Im working on a project and i need AudioSessionNotification::OnSessionCreated too

**Comment by AndreMiras** [comment]
Thanks for contributing.
When you have many commits, you can always squash with `git rebase -i` or `git reset --soft HEAD~<N>`.
I like small pull requests more over big pull requests by the way :wink:

**Comment by TurboAnonym** [comment]
i have no clue 😉

i thought with all this back and forth ... that i should make a new request later and add there also:
```
Get State and OnSessionCreated as well as an example ;)
And add something in to pycaw.pycaw.AudioSession so you can easily access the new functions ;)
```

i thought it would make it easier for you to test all this if its all in one run ;)

... but youre right small is better ;) then you know where possible errors are

**Review by AndreMiras — APPROVED** [review]
Thanks for the hard work and for fixing the linter.
For your info, you can squash commits and push force in order to make a PR with one commit.
I'll squash upon merge

**Comment by TurboAnonym** [comment]
Yeah it was even fun trying all out and fixing it 😁
Thanks for the maintenance of this project and the info 🤗

**Pull request merged**
